// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4XcmXLCvUH-SX0qttLghrfvp9glWKhbw',
    appId: '1:143328590478:android:14c496cae313687cb5a7df',
    messagingSenderId: '143328590478',
    projectId: 'belsante-app',
    storageBucket: 'belsante-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCItKsbzcndqt4BZDIbfQ0HJIXpDlRvnkU',
    appId: '1:143328590478:ios:eef0002cc8fc8ffdb5a7df',
    messagingSenderId: '143328590478',
    projectId: 'belsante-app',
    storageBucket: 'belsante-app.appspot.com',
    androidClientId: '143328590478-fkrhbts5e5566l6js7k4o5ts7s2qv268.apps.googleusercontent.com',
    iosClientId: '143328590478-3kvko916s5anqulis59kmhngg6g8nm5k.apps.googleusercontent.com',
    iosBundleId: 'com.codingwitht.loginFlutterApp',
  );
}
